/**/
define(function(require) {
	return [
		[
			[{
				"url": "../web/img/top-mod/1_40_40.jpg",
				"title": "艾尔战记1",
				"name": "祈Inory",
				"pop": 582
			}, {
				"url": "../web/img/top-mod/2_40_40.jpg",
				"title": "【编曲作品】皆斩（收录于小千专辑千次元）<",
				"name": "GMN-宏宇",
				"pop": 765
			}, {
				"url": "../web/img/top-mod/3_40_40.jpg",
				"title": "黑·风流年间",
				"name": "五色石南叶",
				"pop": 1968
			}, {
				"url": "../web/img/top-mod/4_40_40.jpg",
				"title": "放浪",
				"name": "王洋1976",
				"pop": 186
			}, {
				"url": "../web/img/top-mod/5_40_40.jpg",
				"title": "给未来的你唱首歌",
				"name": "支爽MrZero",
				"pop": 171
			}, {
				"url": "../web/img/top-mod/6_40_40.jpg",
				"title": "《抑郁症》",
				"name": "秦欢的欢乐园",
				"pop": 525
			}, {
				"url": "../web/img/top-mod/7_40_40.jpg",
				"title": "【-古-】『同人』漠言殇（微小说《睡美人..",
				"name": "正版凉夕",
				"pop": 756
			}, {
				"url": "../web/img/top-mod/8_40_40.jpg",
				"title": "归乡Ⅱ",
				"name": "whtlook",
				"pop": 330
			}, {
				"url": "../web/img/top-mod/9_40_40.jpg",
				"title": "认输",
				"name": "Shelly佳.",
				"pop": 495
			}, {
				"url": "../web/img/top-mod/10_40_40.jpg",
				"title": "【重编曲】黑白天鹅-Snow Ver.【言和】",
				"name": "秦欢的欢乐园",
				"pop": 543
			}],
			[{
				"url": "../web/img/top-mod/11_40_40.jpg",
				"title": "走向明天",
				"name": "王媛渊",
				"pop": 138
			}, {
				"url": "../web/img/top-mod/12_40_40.jpg",
				"title": "青丘（《青丘狐传说》手游“狐族圣地”青丘主题歌）",
				"name": "HITA",
				"pop": 948
			}, {
				"url": "../web/img/top-mod/13_40_40.jpg",
				"title": "【策 | 原创·天下3】十方天下--唱：伦桑【平纱落雁】",
				"name": "泪影兽",
				"pop": 1476
			}, {
				"url": "../web/img/top-mod/14_40_40.jpg",
				"title": "幽篁里",
				"name": "Aki阿杰",
				"pop": 3330
			}, {
				"url": "../web/img/top-mod/15_40_40.jpg",
				"title": "矛盾综合体的自白",
				"name": "nRCc1981",
				"pop": 162
			}, {
				"url": "../web/img/top-mod/16_40_40.jpg",
				"title": "DUST 尘埃",
				"name": "Keena_越",
				"pop": 315
			}, {
				"url": "../web/img/top-mod/17_40_40.jpg",
				"title": "篱边秋",
				"name": "横颜君",
				"pop": 3675
			}, {
				"url": "../web/img/top-mod/18_40_40.jpg",
				"title": "【-作词-】祸国（by樱九）",
				"name": "结风",
				"pop": 2901
			}, {
				"url": "../web/img/top-mod/19_40_40.jpg",
				"title": "【木鱼贺年】龙舞",
				"name": "妖卿__",
				"pop": 978
			}, {
				"url": "../web/img/top-mod/20_40_40.jpg",
				"title": "【情人节贺】见亦思牵",
				"name": "Junco_声沙",
				"pop": 1302
			}]
		],
		[
			[{
				"url": "../web/img/top-mod/1_40_40.jpg",
				"title": "艾尔战记2",
				"name": "祈Inory",
				"pop": 582
			}, {
				"url": "../web/img/top-mod/2_40_40.jpg",
				"title": "【编曲作品】皆斩（收录于小千专辑千次元）<",
				"name": "GMN-宏宇",
				"pop": 765
			}, {
				"url": "../web/img/top-mod/3_40_40.jpg",
				"title": "黑·风流年间",
				"name": "五色石南叶",
				"pop": 1968
			}, {
				"url": "../web/img/top-mod/4_40_40.jpg",
				"title": "放浪",
				"name": "王洋1976",
				"pop": 186
			}, {
				"url": "../web/img/top-mod/5_40_40.jpg",
				"title": "给未来的你唱首歌",
				"name": "支爽MrZero",
				"pop": 171
			}, {
				"url": "../web/img/top-mod/6_40_40.jpg",
				"title": "《抑郁症》",
				"name": "秦欢的欢乐园",
				"pop": 525
			}, {
				"url": "../web/img/top-mod/7_40_40.jpg",
				"title": "【-古-】『同人』漠言殇（微小说《睡美人..",
				"name": "正版凉夕",
				"pop": 756
			}, {
				"url": "../web/img/top-mod/8_40_40.jpg",
				"title": "归乡Ⅱ",
				"name": "whtlook",
				"pop": 330
			}, {
				"url": "../web/img/top-mod/9_40_40.jpg",
				"title": "认输",
				"name": "Shelly佳.",
				"pop": 495
			}, {
				"url": "../web/img/top-mod/10_40_40.jpg",
				"title": "【重编曲】黑白天鹅-Snow Ver.【言和】",
				"name": "秦欢的欢乐园",
				"pop": 543
			}],
			[{
				"url": "../web/img/top-mod/11_40_40.jpg",
				"title": "走向明天",
				"name": "王媛渊",
				"pop": 138
			}, {
				"url": "../web/img/top-mod/12_40_40.jpg",
				"title": "青丘（《青丘狐传说》手游“狐族圣地”青丘主题歌）",
				"name": "HITA",
				"pop": 948
			}, {
				"url": "../web/img/top-mod/13_40_40.jpg",
				"title": "【策 | 原创·天下3】十方天下--唱：伦桑【平纱落雁】",
				"name": "泪影兽",
				"pop": 1476
			}, {
				"url": "../web/img/top-mod/14_40_40.jpg",
				"title": "幽篁里",
				"name": "Aki阿杰",
				"pop": 3330
			}, {
				"url": "../web/img/top-mod/15_40_40.jpg",
				"title": "矛盾综合体的自白",
				"name": "nRCc1981",
				"pop": 162
			}, {
				"url": "../web/img/top-mod/16_40_40.jpg",
				"title": "DUST 尘埃",
				"name": "Keena_越",
				"pop": 315
			}, {
				"url": "../web/img/top-mod/17_40_40.jpg",
				"title": "篱边秋",
				"name": "横颜君",
				"pop": 3675
			}, {
				"url": "../web/img/top-mod/18_40_40.jpg",
				"title": "【-作词-】祸国（by樱九）",
				"name": "结风",
				"pop": 2901
			}, {
				"url": "../web/img/top-mod/19_40_40.jpg",
				"title": "【木鱼贺年】龙舞",
				"name": "妖卿__",
				"pop": 978
			}, {
				"url": "../web/img/top-mod/20_40_40.jpg",
				"title": "【情人节贺】见亦思牵",
				"name": "Junco_声沙",
				"pop": 1302
			}]
		],
		[
			[{
				"url": "../web/img/top-mod/1_40_40.jpg",
				"title": "艾尔战记3",
				"name": "祈Inory",
				"pop": 582
			}, {
				"url": "../web/img/top-mod/2_40_40.jpg",
				"title": "【编曲作品】皆斩（收录于小千专辑千次元）<",
				"name": "GMN-宏宇",
				"pop": 765
			}, {
				"url": "../web/img/top-mod/3_40_40.jpg",
				"title": "黑·风流年间",
				"name": "五色石南叶",
				"pop": 1968
			}, {
				"url": "../web/img/top-mod/4_40_40.jpg",
				"title": "放浪",
				"name": "王洋1976",
				"pop": 186
			}, {
				"url": "../web/img/top-mod/5_40_40.jpg",
				"title": "给未来的你唱首歌",
				"name": "支爽MrZero",
				"pop": 171
			}, {
				"url": "../web/img/top-mod/6_40_40.jpg",
				"title": "《抑郁症》",
				"name": "秦欢的欢乐园",
				"pop": 525
			}, {
				"url": "../web/img/top-mod/7_40_40.jpg",
				"title": "【-古-】『同人』漠言殇（微小说《睡美人..",
				"name": "正版凉夕",
				"pop": 756
			}, {
				"url": "../web/img/top-mod/8_40_40.jpg",
				"title": "归乡Ⅱ",
				"name": "whtlook",
				"pop": 330
			}, {
				"url": "../web/img/top-mod/9_40_40.jpg",
				"title": "认输",
				"name": "Shelly佳.",
				"pop": 495
			}, {
				"url": "../web/img/top-mod/10_40_40.jpg",
				"title": "【重编曲】黑白天鹅-Snow Ver.【言和】",
				"name": "秦欢的欢乐园",
				"pop": 543
			}],
			[{
				"url": "../web/img/top-mod/11_40_40.jpg",
				"title": "走向明天",
				"name": "王媛渊",
				"pop": 138
			}, {
				"url": "../web/img/top-mod/12_40_40.jpg",
				"title": "青丘（《青丘狐传说》手游“狐族圣地”青丘主题歌）",
				"name": "HITA",
				"pop": 948
			}, {
				"url": "../web/img/top-mod/13_40_40.jpg",
				"title": "【策 | 原创·天下3】十方天下--唱：伦桑【平纱落雁】",
				"name": "泪影兽",
				"pop": 1476
			}, {
				"url": "../web/img/top-mod/14_40_40.jpg",
				"title": "幽篁里",
				"name": "Aki阿杰",
				"pop": 3330
			}, {
				"url": "../web/img/top-mod/15_40_40.jpg",
				"title": "矛盾综合体的自白",
				"name": "nRCc1981",
				"pop": 162
			}, {
				"url": "../web/img/top-mod/16_40_40.jpg",
				"title": "DUST 尘埃",
				"name": "Keena_越",
				"pop": 315
			}, {
				"url": "../web/img/top-mod/17_40_40.jpg",
				"title": "篱边秋",
				"name": "横颜君",
				"pop": 3675
			}, {
				"url": "../web/img/top-mod/18_40_40.jpg",
				"title": "【-作词-】祸国（by樱九）",
				"name": "结风",
				"pop": 2901
			}, {
				"url": "../web/img/top-mod/19_40_40.jpg",
				"title": "【木鱼贺年】龙舞",
				"name": "妖卿__",
				"pop": 978
			}, {
				"url": "../web/img/top-mod/20_40_40.jpg",
				"title": "【情人节贺】见亦思牵",
				"name": "Junco_声沙",
				"pop": 1302
			}]
		]
	];
});